# Generated by Django 3.2.11 on 2022-01-27 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_category'),
        ('cart', '0002_auto_20220127_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item',
            new_name='CartItem',
        ),
    ]
